name: Conda Upload

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
    - name: publish-to-conda
      uses: darnellgranberry/conda-package-publish-action@master
      with:
        subdir: 'conda-build'
        anacondatoken: ${{ secrets.CONDAAPITOKEN }}